spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 000622m4a1
    url: jdbc:mysql://119.3.235.179:3306/hunyuan_conference?serverTimezone=GMT%2b8&useSSL=false


  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.example.demo: debug

server:
  port: 8080
