spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 000622m4a1
    url: jdbc:mysql://119.3.235.179:3306/meetings?serverTimezone=GMT%2b8&useSSL=false


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.example.demo: debug
